dereine: dawehner
dereine et al: dawehner
rob loach: robloach
david rothstein: david_rothstein
davereid: dave reid
niklas: niklas fiekas
rootatwc: parisliakos
tim.plunkett et al: tim.plunkett
tim.plunket: tim.plunkett
ianmthomasuk: ianthomas_uk
jessebeach et al: jessebeach
aspilicious et al: aspilicious
andypost et al: andypost
neclimdul et al: neclimdul
sun et al: sun
droplet et al: droplet
podarok et al: podarok
damien tournoud et al: damien tournoud
and damien tournoud: damien tournoud
damz: damien tournoud
mrfelton. et al: mrfelton
jasonrsavino et al: jasonrsavino
marcp et all: marcp
fubhy the cat: fubhy
jeroen12345: jeroent
no_commit_credit: xjm
joelpitett: joelpittet
lewis nyman: lewisnyman
lewisnyman bartik: lewisnyman
emma_maria: emma.maria
long wave: longwave
follow up yched: yched
_nod: nod_
nod: nod_
moshe weitzmann: moshe weitzman
javier.alejandr...: javier.alejandro.castro
markcarver: mark carver
dominique clause: dom.
juampy: juampynr
not_chx: chx
davinder.snehi: snehi
nguerrero: nesta_
juanmamr: jmmarquez
gnugeti: gnuget
shashi1028: shashikant_chauhan
